services:
  postgres:
    image: postgres:17
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: linhtrang_payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - payload-postgres-data:/var/lib/postgresql/data
    logging:
      driver: none

volumes:
  payload-postgres-data:
